<a href="https://colab.research.google.com/github/tanishqpanipat/RL/blob/main/Experiment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Define the Q-table with dimensions (6, 6) initialized with zeros
Q = np.zeros((6, 6))

# Define the rewards matrix
rewards = np.array([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1, 0, -1, 100],
    [-1, -1, -1, 0, -1, -1],
    [-1, 0, 0, -1, 0, -1],
    [0, -1, -1, 0, -1, 100],
    [-1, 0, -1, -1, 0, 100]

])

# Define hyperparameters
learning_rate = 0.8
discount_factor = 0.95
num_episodes = 1000

# Q-learning algorithm
for _ in range(num_episodes):
    current_state = np.random.randint(6)  # Start in a random state

    while current_state != 5:  # While not in the goal state (state 5)
        # Choose a random valid action
        possible_actions = np.where(rewards[current_state] >= 0)[0]
        action = np.random.choice(possible_actions)

        # Update Q-value using the Q-learning formula
        next_state = action
        max_next_action = np.argmax(Q[next_state])
        Q[current_state, action] = (1 - learning_rate) * Q[current_state, action] + learning_rate * (rewards[current_state, action] + discount_factor * Q[next_state, max_next_action])

        current_state = next_state

# Print the learned Q-table
print("Learned Q-Table:")
print(Q)

# Optimal policy
current_state = 2  # Starting state
path = [current_state]

while current_state != 5:  # While not in the goal state (state 5)
    action = np.argmax(Q[current_state])
    current_state = action
    path.append(current_state)

print("Optimal Path:")
print(path)


Learned Q-Table:
[[  0.       0.       0.       0.      95.       0.    ]
 [  0.       0.       0.      90.25     0.     100.    ]
 [  0.       0.       0.      90.25     0.       0.    ]
 [  0.      95.      85.7375   0.      95.       0.    ]
 [ 90.25     0.       0.      90.25     0.     100.    ]
 [  0.       0.       0.       0.       0.       0.    ]]
Optimal Path:
[2, 3, 1, 5]


In [2]:
import numpy as np

# Define the Q-table with dimensions (6, 6) initialized with zeros
Q = np.zeros((6, 6))

# Define the rewards matrix
rewards = np.array([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1, 0, -1, 100],
    [-1, -1, -1, 0, -1, -1],
    [-1, 0, 0, -1, 0, -1],
    [0, -1, -1, 0, -1, 100],
    [-1, 0, -1, -1, 0, 100]
])

# Define hyperparameters
learning_rate = 0.8
discount_factor = 0.95
num_episodes = 1000

# Q-learning algorithm
for episode in range(num_episodes):
    current_state = np.random.randint(6)  # Start in a random state

    while current_state != 5:  # While not in the goal state (state 5)
        # Choose a random valid action
        possible_actions = np.where(rewards[current_state] >= 0)[0]
        action = np.random.choice(possible_actions)

        # Update Q-value using the Q-learning formula
        next_state = action
        max_next_action = np.argmax(Q[next_state])
        Q[current_state, action] = (1 - learning_rate) * Q[current_state, action] + learning_rate * (rewards[current_state, action] + discount_factor * Q[next_state, max_next_action])

        current_state = next_state

        # Print the Q-table at each time step
        if episode % 100 == 0:
            print(f"Episode {episode} - Q-Table:")
            print(Q)

# Print the final learned Q-table
print("Final Q-Table:")
print(Q)

# Optimal policy
current_state = 2  # Starting state
path = [current_state]

while current_state != 5:  # While not in the goal state (state 5)
    action = np.argmax(Q[current_state])
    current_state = action
    path.append(current_state)

print("Optimal Path:")
print(path)

Episode 0 - Q-Table:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Episode 0 - Q-Table:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Episode 0 - Q-Table:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Episode 0 - Q-Table:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Episode 0 - Q-Table:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Episode 0 - Q-Table:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Episode 0 - Q-Table:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0.